language: rust

# TODO: find a way to install SDL2 without sudo and disable it:
sudo: true

cache: cargo

rust:
    - nightly
    - stable

matrix:
    allow_failures:
        - rust: nightly

os:
    - linux
    - osx
    - windows

addons:
  apt:
    update: true
    packages:
    - libasound2-dev

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
        && tar -xzvf SDL2-2.0.5.tar.gz
        && pushd SDL2-2.0.5
        && ./configure --prefix=/usr
        && make
        && sudo make install
        && popd;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update && brew install sdl2;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
        curl -O https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip
        && ls
        && 7z x SDL2-devel-2.0.5-VC.zip
        && ls
        && cp SDL2-2.0.5/lib/x64/* .
        && ls;
    fi

before_script:
  - rustup component list

script:
    - cargo build
    - make test
    - cargo build --release

jobs:
  include:
  - name: fmt
    rust: stable
    install:
      - rustup component add rustfmt
      - rustfmt -V
      - rustup component add clippy
      - cargo clippy -V
    script:
      - make lint
      - cargo clippy --verbose -- -D warnings
